# This is a basic workflow to help you get started with Actions

library(oibiostat)
? prevend
#I think we should change the name 

library(oibiostat)
data("prevend")
attach(prevend)

table(prevend$Gender)
prop.table(table(prevend$Gender))

summary(prevend$BMI)

mean(Age)
sd(Age)
summary(Age)

table(prevend$Ethnicity)
table(prevend$Education)


mean(RFFT)
sd(RFFT)

median(VAT)
IQR(VAT)

table(prevend$Statin)
table(prevend$DM)
table(prevend$Smoking)
table(prevend$Hypertension)

mean(FRS)
sd(FRS)

prop.table(table(prevend$Age))
#^percentage per age 
hist(prevend$Age)
table(prevend$Age)
#^count per age 
count(prevend$Age)

prop.table(table(prevend$Smoking))

table(prevend$HDL)

mean(HDL)
sd(HDL)
mean(prevend$HDL[prevend$HDL != "-1"])
sd(prevend$HDL[prevend$HDL != "-1"])

prop.table(table(prevend$Ethnicity))

3958+30+3+34 
2140+1955

prop.table(table(prevend$Education))

3788+307
prop.table(table(prevend$CVD))

3840+255 

22+3101+972





prop.table(table(prevend$DM))

2706+1389 
prop.table(table(prevend$Hypertension))

3499+596
prop.table(table(prevend$Albuminuria.1))

3191+904
prop.table(table(prevend$Statin))

